name: ASP.NET Core Tests

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: dotnet restore "/src/Módulo de autorização e autenticação.csproj"

      - name: Build
        run: dotnet build "/src/Módulo de autorização e autenticação.csproj" --no-restore --configuration realease

      - name: Run tests
        run: dotnet test "/src/Módulo de autorização e autenticação.csproj" --no-build --verbosity normal

